/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

var BOARD = new Board();

function load() {
  dashcode.setupParts();
  BOARD.load();
}

function remove() {
  BOARD.remove();
}

function hide() {
}

function show() {
  BOARD.show();
}

function sync() {
}

function showBack(event) {
  var front = document.getElementById("front");
  var back = document.getElementById("back");

  if (window.widget) {
      widget.prepareForTransition("ToBack");
  }

  front.style.display = "none";
  back.style.display = "block";

  if (window.widget) {
      setTimeout('widget.performTransition();', 0);
  }
}

function showFront(event) {
  var front = document.getElementById("front");
  var back = document.getElementById("back");

  if (window.widget) {
      widget.prepareForTransition("ToFront");
  }

  front.style.display="block";
  back.style.display="none";

  if (window.widget) {
      setTimeout('widget.performTransition();', 0);
      document.getElementById('scrollArea').object.refresh();
  }
}

if (window.widget) {
  widget.onremove = remove;
  widget.onhide = hide;
  widget.onshow = show;
  widget.onsync = sync;
}
